stages:
  # --- Evaluation Scoring (Maps Only) ---
  - name: evalmaps
    stage: evaluation
    run_ids:
      - qhuhodtq
      - d0idcy7b
    eval_config: config/evaluate/eval_config_maps_only.yml
    nodes: 1
    slurm_args:
      - "--time=01:00:00"
      - "--ntasks=1"
      - "--cpus-per-task=36"
