healpix_level: 6
rope_2D: False

# Data streams
streams_directory: "./config/streams/era5_1deg/" # Update if you have a 0.25deg stream!
zarr_store: "zip"
data_path_anemoi: "/e/data1/slmet/ml_training"

training_config:
  num_mini_epochs: 8
  max_compute_budget_l6_steps: 32768
  
wgtags:
  exp: "coarse_to_fine_baseline"
  issue: null
