healpix_level: 6
rope_2D: False

# Data streams
streams_directory: "./config/streams/era5_1deg/" # Update if you have a 0.25deg stream!
zarr_store: "zip"

training_config:
  num_mini_epochs: 32
  max_compute_budget_l6_steps: 131072
  
wgtags:
  exp: "coarse_to_fine_baseline"
  issue: null
