healpix_level: 5
rope_2D: False

# Data streams
streams_directory: "./config/streams/era5_2deg/"
zarr_store: "zip"
data_path_anemoi: "/e/scratch/weatherai/hauer1"

wgtags:
  exp: "coarse_to_fine_multistage"
  stage: "L5"
  issue: null
