healpix_level: 3
rope_2D: False

# Data streams
streams_directory: "./config/streams/era5_8deg/"
zarr_store: "zip"
data_path_anemoi: "/e/scratch/weatherai/hauer1"

wgtags:
  exp: "coarse_to_fine_multistage"
  stage: "L3"
  issue: null
